// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.Data;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(MyStoreDbContext))]
    [Migration("20250504083246_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanhGiaSanPhamNguoiDung", b =>
                {
                    b.Property<int>("DanhSachDanhGiaYeuThichMaDanhGiaSP")
                        .HasColumnType("int");

                    b.Property<string>("DanhSachNguoiYeuThichId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DanhSachDanhGiaYeuThichMaDanhGiaSP", "DanhSachNguoiYeuThichId");

                    b.HasIndex("DanhSachNguoiYeuThichId");

                    b.ToTable("DanhGiaSanPhamNguoiDung");
                });

            modelBuilder.Entity("DanhSachYeuThichSanPham", b =>
                {
                    b.Property<int>("DanhSachSanPhamMaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("DanhSachYeuThichMaDanhSachYeuThich")
                        .HasColumnType("int");

                    b.HasKey("DanhSachSanPhamMaSanPham", "DanhSachYeuThichMaDanhSachYeuThich");

                    b.HasIndex("DanhSachYeuThichMaDanhSachYeuThich");

                    b.ToTable("DanhSachYeuThichSanPham");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "35bd40e4-59ef-466d-9ceb-a27642a7bb40",
                            ConcurrencyStamp = "1",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "184454e1-837c-401a-b2b0-a1f57a096c18",
                            ConcurrencyStamp = "1",
                            Name = "CUSTOMER",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "7d97bcd6-67c6-42ba-aa59-9db2a4eb9e0e",
                            ConcurrencyStamp = "1",
                            Name = "EMPLOYEE",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "79833be7-845e-48e5-895f-9263b24b1783",
                            RoleId = "35bd40e4-59ef-466d-9ceb-a27642a7bb40"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("back_end.Core.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("HinhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiAn")
                        .HasColumnType("bit");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.Property<string>("VanBanTho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaiViet");

                    b.HasIndex("MaTacGia");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("back_end.Core.Models.BienTheSanPham", b =>
                {
                    b.Property<int>("MaBienTheSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienTheSanPham"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKichThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaMauSac")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaBienTheSanPham");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMauSac");

                    b.HasIndex("MaSanPham");

                    b.ToTable("BienTheSanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCTDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDH"));

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("MaBienTheSP")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("MaCTDH");

                    b.HasIndex("MaBienTheSP");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGiaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGiaSP"));

                    b.Property<string>("MaNguoiDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDanhGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSaoDanhGia")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGiaSP");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("NguoiDanhGiaId");

                    b.ToTable("DanhGiaSanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<int?>("DanhMucChaMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaDanhMucCha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("DanhMucChaMaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhSachYeuThich", b =>
                {
                    b.Property<int>("MaDanhSachYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhSachYeuThich"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDanhSachYeuThich");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("DanhSachYeuThichs");
                });

            modelBuilder.Entity("back_end.Core.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("MaDCGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDCGH"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDCGH");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DiaChiGiaoHangs");
                });

            modelBuilder.Entity("back_end.Core.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDiaChiGiaoHang")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaThanhToan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaDiaChiGiaoHang");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaThanhToan")
                        .IsUnique();

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("back_end.Core.Models.HienThiBanner", b =>
                {
                    b.Property<int>("MaHienThiBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHienThiBanner"));

                    b.Property<string>("DuongDanhAnhNen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutHanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHienThiBanner");

                    b.ToTable("HienThiBanners");
                });

            modelBuilder.Entity("back_end.Core.Models.HienThiDanhGia", b =>
                {
                    b.Property<int>("MaHienThiDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHienThiDanhGia"));

                    b.Property<int>("MaDanhGiaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaHienThiDanhGia");

                    b.HasIndex("MaDanhGiaSanPham");

                    b.ToTable("HienThiDanhGias");
                });

            modelBuilder.Entity("back_end.Core.Models.HinhAnhBienTheSanPham", b =>
                {
                    b.Property<int>("MaHinhAnhBienTheSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnhBienTheSanPham"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBienTheSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnhBienTheSanPham");

                    b.HasIndex("MaBienTheSanPham");

                    b.ToTable("HinhAnhBienTheSanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaHinhAnhSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnhSanPham"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnhSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HinhAnhSanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.KichThuoc", b =>
                {
                    b.Property<int>("MaKichThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKichThuoc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaKichThuoc");

                    b.ToTable("KichThuocs");
                });

            modelBuilder.Entity("back_end.Core.Models.LichSuDonHang", b =>
                {
                    b.Property<int>("MaLichSuDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSuDonHang"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanVienId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ThoiGianChinhSua")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichSuDonHang");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("NhanVienId");

                    b.ToTable("LichSuDonHangs");
                });

            modelBuilder.Entity("back_end.Core.Models.MauSac", b =>
                {
                    b.Property<int>("MaMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMauSac"));

                    b.Property<string>("MaThapLucPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaMauSac");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("back_end.Core.Models.NguoiDung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianHoatDongGanDay")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.Property<bool>("TrangThaiKhoa")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "79833be7-845e-48e5-895f-9263b24b1783",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "261403ff-19e5-434b-bc25-37228f82a057",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            HoVaTen = "Thanh Nương",
                            LockoutEnabled = false,
                            NgayTao = new DateTime(2025, 5, 4, 15, 32, 46, 254, DateTimeKind.Local).AddTicks(5216),
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBMjroJIF61fFWxnh1fKePjm4OsO2za5932M0v2nIk1YG6pdxvHmZKcbgZI/LKsZGg==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8cc5fa86-c7d1-4fb9-ae05-ce8e49185853",
                            ThoiGianHoatDongGanDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThaiHoatDong = false,
                            TrangThaiKhoa = false,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("back_end.Core.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("back_end.Core.Models.NhaSanXuat", b =>
                {
                    b.Property<int>("MaNhaSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaSX"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhaSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhaSX");

                    b.ToTable("NhaSanXuats");
                });

            modelBuilder.Entity("back_end.Core.Models.NhanHieu", b =>
                {
                    b.Property<int>("MaNhanHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanHieu"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaNhanHieu");

                    b.ToTable("NhanHieus");
                });

            modelBuilder.Entity("back_end.Core.Models.NhomChat", b =>
                {
                    b.Property<string>("MaNhomChat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTinNhan")
                        .HasColumnType("int");

                    b.Property<int>("SoTinNhanChuaDoc")
                        .HasColumnType("int");

                    b.HasKey("MaNhomChat");

                    b.HasIndex("MaTinNhan")
                        .IsUnique();

                    b.ToTable("NhomChats");
                });

            modelBuilder.Entity("back_end.Core.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<double>("GiaCu")
                        .HasColumnType("float");

                    b.Property<double>("GiaHienTai")
                        .HasColumnType("float");

                    b.Property<double>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<string>("HinhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhPhongTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaSanXuat")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiXoa")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNhaSanXuat");

                    b.HasIndex("MaNhanHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaThanhToan");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("back_end.Core.Models.ThietBiThongBao", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThietBiThongBaos");
                });

            modelBuilder.Entity("back_end.Core.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaThamChieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiDoc")
                        .HasColumnType("bit");

                    b.HasKey("MaThongBao");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("back_end.Core.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<string>("MaNguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiDoc")
                        .HasColumnType("bit");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("back_end.Core.Models.TinNhanHinhAnh", b =>
                {
                    b.Property<int>("MaTinNhanHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhanHinhAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTinNhan")
                        .HasColumnType("int");

                    b.HasKey("MaTinNhanHinhAnh");

                    b.HasIndex("MaTinNhan");

                    b.ToTable("HinhAnhTinNhans");
                });

            modelBuilder.Entity("DanhGiaSanPhamNguoiDung", b =>
                {
                    b.HasOne("back_end.Core.Models.DanhGiaSanPham", null)
                        .WithMany()
                        .HasForeignKey("DanhSachDanhGiaYeuThichMaDanhGiaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("DanhSachNguoiYeuThichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DanhSachYeuThichSanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("DanhSachSanPhamMaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.DanhSachYeuThich", null)
                        .WithMany()
                        .HasForeignKey("DanhSachYeuThichMaDanhSachYeuThich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end.Core.Models.BaiViet", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "TacGia")
                        .WithMany("DanhSachBaiViet")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("back_end.Core.Models.BienTheSanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.KichThuoc", "KichThuoc")
                        .WithMany("ProductVariants")
                        .HasForeignKey("MaKichThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.MauSac", "MauSac")
                        .WithMany("DanhSachBienTheSP")
                        .HasForeignKey("MaMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.SanPham", "SanPham")
                        .WithMany("DanhSachBienTheSP")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KichThuoc");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("back_end.Core.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("DanhSachChiTietDonHang")
                        .HasForeignKey("MaBienTheSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.DonHang", "DonHang")
                        .WithMany("DanhSachChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.SanPham", "SanPham")
                        .WithMany("DanhSachDanhGia")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiDanhGia")
                        .WithMany("DanhSachDanhGia")
                        .HasForeignKey("NguoiDanhGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDanhGia");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhMuc", b =>
                {
                    b.HasOne("back_end.Core.Models.DanhMuc", "DanhMucCha")
                        .WithMany("DanhSachDanhMucCon")
                        .HasForeignKey("DanhMucChaMaDanhMuc");

                    b.Navigation("DanhMucCha");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhSachYeuThich", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiDung")
                        .WithOne("DanhSachYeuThich")
                        .HasForeignKey("back_end.Core.Models.DanhSachYeuThich", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("back_end.Core.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDiaChiGiaoHang")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("back_end.Core.Models.DonHang", b =>
                {
                    b.HasOne("back_end.Core.Models.DiaChiGiaoHang", "DiaChiGiaoHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaDiaChiGiaoHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDonHang")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.ThanhToan", "ThanhToan")
                        .WithOne("DonHang")
                        .HasForeignKey("back_end.Core.Models.DonHang", "MaThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaChiGiaoHang");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("back_end.Core.Models.HienThiDanhGia", b =>
                {
                    b.HasOne("back_end.Core.Models.DanhGiaSanPham", "DanhGiaSanPham")
                        .WithMany()
                        .HasForeignKey("MaDanhGiaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhGiaSanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.HinhAnhBienTheSanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.BienTheSanPham", "BienTheSanPham")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("MaBienTheSanPham");

                    b.Navigation("BienTheSanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.SanPham", "SanPham")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("MaSanPham");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.LichSuDonHang", b =>
                {
                    b.HasOne("back_end.Core.Models.DonHang", "DonHang")
                        .WithMany("LichSuDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId");

                    b.Navigation("DonHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("back_end.Core.Models.NhomChat", b =>
                {
                    b.HasOne("back_end.Core.Models.TinNhan", "TinNhanGanDay")
                        .WithOne("NhomChat")
                        .HasForeignKey("back_end.Core.Models.NhomChat", "MaTinNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinNhanGanDay");
                });

            modelBuilder.Entity("back_end.Core.Models.SanPham", b =>
                {
                    b.HasOne("back_end.Core.Models.DanhMuc", "DanhMuc")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("MaDanhMuc");

                    b.HasOne("back_end.Core.Models.NhaSanXuat", "NhaSanXuat")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("MaNhaSanXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NhanHieu", "NhanHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhanHieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaSanXuat");

                    b.Navigation("NhanHieu");
                });

            modelBuilder.Entity("back_end.Core.Models.ThietBiThongBao", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachThietBiThongBao")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("back_end.Core.Models.ThongBao", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiNhan")
                        .WithMany("DanhSachThongBao")
                        .HasForeignKey("NguoiNhanId");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("back_end.Core.Models.TinNhan", b =>
                {
                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiGui")
                        .WithMany("DanhSachTinNhanDaGui")
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.Core.Models.NguoiDung", "NguoiNhan")
                        .WithMany("DanhSachTinNhanDaNhan")
                        .HasForeignKey("MaNguoiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("back_end.Core.Models.TinNhanHinhAnh", b =>
                {
                    b.HasOne("back_end.Core.Models.TinNhan", "TinNhan")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("MaTinNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinNhan");
                });

            modelBuilder.Entity("back_end.Core.Models.BienTheSanPham", b =>
                {
                    b.Navigation("DanhSachChiTietDonHang");

                    b.Navigation("DanhSachHinhAnh");
                });

            modelBuilder.Entity("back_end.Core.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhSachDanhMucCon");

                    b.Navigation("DanhSachSanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.DiaChiGiaoHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("back_end.Core.Models.DonHang", b =>
                {
                    b.Navigation("DanhSachChiTietDonHang");

                    b.Navigation("LichSuDonHang");
                });

            modelBuilder.Entity("back_end.Core.Models.KichThuoc", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("back_end.Core.Models.MauSac", b =>
                {
                    b.Navigation("DanhSachBienTheSP");
                });

            modelBuilder.Entity("back_end.Core.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhSachBaiViet");

                    b.Navigation("DanhSachDanhGia");

                    b.Navigation("DanhSachDiaChiGiaoHang");

                    b.Navigation("DanhSachDonHang");

                    b.Navigation("DanhSachThietBiThongBao");

                    b.Navigation("DanhSachThongBao");

                    b.Navigation("DanhSachTinNhanDaGui");

                    b.Navigation("DanhSachTinNhanDaNhan");

                    b.Navigation("DanhSachYeuThich")
                        .IsRequired();
                });

            modelBuilder.Entity("back_end.Core.Models.NhaSanXuat", b =>
                {
                    b.Navigation("DanhSachSanPham");
                });

            modelBuilder.Entity("back_end.Core.Models.NhanHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("back_end.Core.Models.SanPham", b =>
                {
                    b.Navigation("DanhSachBienTheSP");

                    b.Navigation("DanhSachDanhGia");

                    b.Navigation("DanhSachHinhAnh");
                });

            modelBuilder.Entity("back_end.Core.Models.ThanhToan", b =>
                {
                    b.Navigation("DonHang")
                        .IsRequired();
                });

            modelBuilder.Entity("back_end.Core.Models.TinNhan", b =>
                {
                    b.Navigation("DanhSachHinhAnh");

                    b.Navigation("NhomChat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
